name: card_holder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.2.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
