// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSryrsXebLAT4lmhImk8PS3dMcSfW4fps',
    appId: '1:1007378601003:web:a24035a0e276e79aba066e',
    messagingSenderId: '1007378601003',
    projectId: 'online-pay-8c4e8',
    authDomain: 'online-pay-8c4e8.firebaseapp.com',
    storageBucket: 'online-pay-8c4e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5v-_P9TlMTibzPbojuGBiztwqqym3bHI',
    appId: '1:1007378601003:android:2610d9dd02c173f7ba066e',
    messagingSenderId: '1007378601003',
    projectId: 'online-pay-8c4e8',
    storageBucket: 'online-pay-8c4e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk_kmjloWjux9ITENfrbpBPdvAiw1TMAI',
    appId: '1:1007378601003:ios:1a64db429d125018ba066e',
    messagingSenderId: '1007378601003',
    projectId: 'online-pay-8c4e8',
    storageBucket: 'online-pay-8c4e8.appspot.com',
    iosBundleId: 'com.example.cardHolder',
  );
}
